apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: quality

resources:
  - configmap.yaml
  - secret.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml

commonLabels:
  app.kubernetes.io/name: sonarqube
  app.kubernetes.io/part-of: quality-stack
  app.kubernetes.io/managed-by: kustomize