apiVersion: v1
kind: Secret
metadata:
  name: sonarqube-secrets
  namespace: quality
  labels:
    app: sonarqube
type: Opaque
stringData:
  # Database - usando PostgreSQL RDS
  SONAR_JDBC_URL: "jdbc:postgresql://product-comparison-dev-db.xxxxx.us-east-1.rds.amazonaws.com:5432/sonarqube"
  SONAR_JDBC_USERNAME: "sonarqube"
  SONAR_JDBC_PASSWORD: "SonarQube135246!"