apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  spec:
    replicas: 2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-service
  spec:
    replicas: 2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-service
  spec:
    replicas: 2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  spec:
    replicas: 2