apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: product-comparison-ingress
  namespace: product-platform
  labels:
    app.kubernetes.io/part-of: product-comparison
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:347277718217:certificate/fe0f2f22-4b69-4674-b2e4-90665101a010
    alb.ingress.kubernetes.io/healthcheck-path: /actuator/health
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: "30"
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: "5"
    alb.ingress.kubernetes.io/healthy-threshold-count: "2"
    alb.ingress.kubernetes.io/unhealthy-threshold-count: "3"
    alb.ingress.kubernetes.io/waf-acl-arn: arn:aws:wafv2:us-east-1:347277718217:regional/webacl/product-comparison-dev-waf/05cd160d-0538-43cd-8e54-1b8a0bb7b7ae
    alb.ingress.kubernetes.io/group.name: product-comparison
spec:
  ingressClassName: alb
  rules:
    - host: api.cognitiva.solutions
      http:
        paths:
          - path: /api/products
            pathType: Prefix
            backend:
              service:
                name: product-service
                port:
                  number: 8080
          - path: /api/search
            pathType: Prefix
            backend:
              service:
                name: search-service
                port:
                  number: 8082
          - path: /api/ai
            pathType: Prefix
            backend:
              service:
                name: ai-service
                port:
                  number: 8081