apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - alb-controller/
  - ingress-apps.yaml
  - ingress-monitoring.yaml
  - ingress-quality.yaml
  - ingress-argocd.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize