apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: finops

resources:
  - namespace.yaml
  - cost-exporter/
  - grafana-dashboard/cost-dashboard.yaml

commonLabels:
  app.kubernetes.io/part-of: finops
  app.kubernetes.io/managed-by: kustomize