apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: product-platform
  labels:
    app: frontend
    app.kubernetes.io/name: frontend
    app.kubernetes.io/part-of: product-comparison
data:
  NODE_ENV: "production"
  NEXT_PUBLIC_API_URL: "https://api.cognitiva.solutions"
  NEXT_PUBLIC_SEARCH_API_URL: "https://search.cognitiva.solutions"