apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Todos os recursos do projeto
resources:
  - base/
  - apps/
  - monitoring/
  - quality/
  - data/
  - argocd/
  - ingress/
  - security/

commonLabels:
  app.kubernetes.io/part-of: product-comparison
  app.kubernetes.io/managed-by: kustomize