apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend
  namespace: argocd
  labels:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/part-of: product-comparison
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: product-platform
  
  source:
    repoURL: https://github.com/vynnydev/product-comparison-platform.git
    targetRevision: HEAD
    path: k8s/apps/frontend
  
  destination:
    server: https://kubernetes.default.svc
    namespace: product-platform
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m