apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: security

resources:
  - namespace.yaml
  - security-dashboard/
  - alerting/
  - aws-integration/
  - disaster-recovery/

commonLabels:
  app.kubernetes.io/part-of: security-stack
  app.kubernetes.io/managed-by: kustomize