apiVersion: v1
kind: Secret
metadata:
  name: search-service-secrets
  namespace: product-platform
  labels:
    app: search-service
    app.kubernetes.io/name: search-service
    app.kubernetes.io/part-of: product-comparison
type: Opaque
stringData:
  # ElastiCache Redis
  REDIS_HOST: "product-comparison-dev-redis.xxxxx.cache.amazonaws.com"
  REDIS_PASSWORD: ""
  
  # OpenSearch
  OPENSEARCH_HOST: "vpc-prod-comp-dev-search-xxxxx.us-east-1.es.amazonaws.com"
  OPENSEARCH_PASSWORD: "ProdCompPlat135246OpenSearch!"