apiVersion: v1
kind: Service
metadata:
  name: search-service
  namespace: product-platform
  labels:
    app: search-service
    app.kubernetes.io/name: search-service
    app.kubernetes.io/part-of: product-comparison
spec:
  type: ClusterIP
  selector:
    app: search-service
  ports:
    - name: http
      port: 8082
      targetPort: 8082
      protocol: TCP