apiVersion: v1
kind: ServiceAccount
metadata:
  name: search-service-sa
  namespace: product-platform
  labels:
    app: search-service
    app.kubernetes.io/name: search-service
    app.kubernetes.io/part-of: product-comparison
  # annotations:
  #   eks.amazonaws.com/role-arn: arn:aws:iam::347277718217:role/search-service-role