apiVersion: v1
kind: ServiceAccount
metadata:
  name: ai-service-sa
  namespace: product-platform
  labels:
    app: ai-service
    app.kubernetes.io/name: ai-service
    app.kubernetes.io/part-of: product-comparison
  #annotations:
    # IRSA para Bedrock - descomentar após criar role no Terraform
    # eks.amazonaws.com/role-arn: arn:aws:iam::347277718217:role/ai-service-bedrock-role