apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: security

resources:
  - slack-webhook-secret.yaml
  - discord-webhook-secret.yaml
  # - pagerduty-secret.yaml
  - alertmanager-config.yaml
  - prometheus-rules.yaml

commonLabels:
  app.kubernetes.io/name: alerting
  app.kubernetes.io/part-of: security-stack