# REMOVA O EXAMPLE DO FINAL DO NOME DO ARQUIVO
apiVersion: v1
kind: Secret
metadata:
  name: pagerduty-config
  namespace: security
  labels:
    app: alerting
type: Opaque
stringData:
  # Substitua pela chave real do PagerDuty
  PAGERDUTY_SERVICE_KEY: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
  PAGERDUTY_URL: "https://events.pagerduty.com/v2/enqueue"