apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: quality

resources:
  - namespace.yaml
  - sonarqube/

commonLabels:
  app.kubernetes.io/part-of: quality-stack
  app.kubernetes.io/managed-by: kustomize