apiVersion: v1
kind: Namespace
metadata:
  name: security
  labels:
    app.kubernetes.io/name: security
    app.kubernetes.io/part-of: product-comparison
    purpose: security-monitoring
    pod-security.kubernetes.io/enforce: restricted