apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: product-platform
  namespace: argocd
  labels:
    app.kubernetes.io/name: product-platform
    app.kubernetes.io/part-of: product-comparison
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: "Product Comparison Platform Project"
  
  # Repositórios permitidos
  sourceRepos:
    - "https://github.com/vynnydev/product-comparison-platform.git"
    - "*"
  
  # Destinos permitidos
  destinations:
    - namespace: product-platform
      server: https://kubernetes.default.svc
    - namespace: monitoring
      server: https://kubernetes.default.svc
    - namespace: data
      server: https://kubernetes.default.svc
    - namespace: quality
      server: https://kubernetes.default.svc
  
  # Recursos permitidos
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
  
  # Recursos de namespace permitidos
  namespaceResourceWhitelist:
    - group: ""
      kind: "*"
    - group: apps
      kind: "*"
    - group: autoscaling
      kind: "*"
    - group: networking.k8s.io
      kind: "*"
    - group: batch
      kind: "*"
  
  # Roles
  roles:
    - name: developer
      description: "Developer role"
      policies:
        - p, proj:product-platform:developer, applications, get, product-platform/*, allow
        - p, proj:product-platform:developer, applications, sync, product-platform/*, allow
      groups:
        - developers
    
    - name: admin
      description: "Admin role"
      policies:
        - p, proj:product-platform:admin, applications, *, product-platform/*, allow
      groups:
        - admins