apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-load-balancer-controller
  namespace: kube-system
  labels:
    app.kubernetes.io/name: aws-load-balancer-controller
    app.kubernetes.io/component: controller
  annotations:
    # ARN da IAM Role criada pelo Terraform
    eks.amazonaws.com/role-arn: arn:aws:iam::347277718217:role/aws-load-balancer-controller-role