apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - namespace.yaml
  - install/
  - config/
  - projects/
  # Não incluir apps aqui - usar app-of-apps

commonLabels:
  app.kubernetes.io/part-of: argocd
  app.kubernetes.io/managed-by: kustomize