apiVersion: v1
kind: Secret
metadata:
  name: opensearch-credentials
  namespace: product-platform
  labels:
    app.kubernetes.io/part-of: product-comparison
type: Opaque
stringData:
  OPENSEARCH_USERNAME: "admin"
  OPENSEARCH_PASSWORD: "SENHA"
  # Connection string completa
  OPENSEARCH_URL: "https://admin:SENHA@vpc-prod-comp-dev-search-lf4ult6kxxzmexenf4la7omhe4.us-east-1.es.amazonaws.com:443"