# REMOVA O EXAMPLE DO FINAL DO NOME DO ARQUIVO
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-credentials
  namespace: product-platform
  labels:
    app.kubernetes.io/part-of: product-comparison
type: Opaque
stringData:
  RABBITMQ_USERNAME: "admin"
  RABBITMQ_PASSWORD: "SENHA"