apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cognitiva-analytics

resources:
  - namespace.yaml
  - configmap.yaml
  - identity-service.yaml
  - asset-service.yaml
  - operations-service.yaml
  - supply-chain-service.yaml
  - platform-service.yaml

commonLabels:
  app.kubernetes.io/part-of: challenge
  app.kubernetes.io/managed-by: kustomize
  project: cognitiva-analytics